#!/bin/bash
 cd GnGG_setup
 git clone https://github.com/adc0032/GrabNGoGenomes.git ;
 export PATH=${PATH}:$HOME/GrabNGoGenomes >& /dev/null || setenv PATH "${PATH}:$HOME/GrabNGoGenomes"
 
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bashrc.local
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bash_profile
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bashrc

#Downloads Entrez E-Utilities

cd ~
  /bin/bash
  perl -MNet::FTP -e \
    '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1);
     $ftp->login; $ftp->binary;
     $ftp->get("/entrez/entrezdirect/edirect.tar.gz");'
  gunzip -c edirect.tar.gz | tar xf -
  rm edirect.tar.gz
  builtin exit
  export PATH=${PATH}:$HOME/edirect >& /dev/null || setenv PATH "${PATH}:$HOME/edirect"
  ./edirect/setup.sh ;

#Statement to add edirect to path in configuration files

 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bashrc.local
 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bash_profile
 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bashrc

