#!/bin/bash

edinstall=$(echo $PATH | grep -c "edirect")

if [[ $edinstall -gt 0 ]]; then
 cd $HOME
 git clone https://github.com/adc0032/GrabNGoGenomes.git ;


if [[ -e .bashrc_local ]]; then
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bashrc.local
 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bashrc.local
 source $HOME/.bashrc.local
elif [[ -e .bash_profile ]]; then 
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bash_profile
 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bash_profile
 source $HOME/.bash_profile
elif [[ -e .bashrc ]]; then
 echo "export PATH=\$PATH:\$HOME/GrabNGoGenomes" >> $HOME/.bashrc
 echo "export PATH=\$PATH:\$HOME/edirect" >> $HOME/.bashrc
 source $HOME/.bashrc
fi

echo ""
echo ""

 echo "GrabNGoGenomes Setup Complete!"
 echo "Copy the following command into the terminal to finalize setup: export PATH=\$PATH:\$HOME/GrabNGoGenomes >& /dev/null || setenv PATH "\$PATH:\$HOME/GrabNGoGenomes""
 echo ""
 echo "Once complete, try running command get_SeqRec -h | get_SeqRec to get started"
else
 echo ""
 echo "Commands in ~/GnGG_setup/setup_edirect must be copied and pasted into your terminal before running this script" 
 echo ""
 echo "Once user pastes commands from the setup_edirect to the terminal, the following message is expect: "
 echo ""
 echo ""
 echo "\"Please be patient, as this step may take a little while. Entrez Direct has been successfully downloaded and installed...\""
 echo ""
 echo ""
 echo "User does not need to run the output command given from pasting setup_edirect code to terminal, those steps are completed in setup_GnGG."
 exit 0
fi
